### PR TITLE
Get active parcel nft user address and display in PlotDetail/popup

### PR DESCRIPTION
**Pull request by ssdsr**
Use the Opensea API (https://docs.opensea.io/reference/retrieving-a-single-asset) to retrieve asset data and render the user address in PlotDetail/Map popup.

You may have to add an API key in your env variables to get less aggressive rate limiting from the Opensea API.

### CODE REVIEW

**Comment by trkaplan** [comment]
@ssdsr It sends two requests when clicking on a plot. Can you check it? 
image

**Comment by blackeagle0188** [comment]
The popup for the first selected plot does not show the owner address.
image

**Comment by blackeagle0188** [comment]
@ssdsr It shows different owner addresses.
image
image

**Comment by blackeagle0188** [comment]
> Did you check the console / network tab? I think it is because when clicking on the map it send two requests and this may cause the API to reject the request. Even we have an API key, we need a proxy API to cache requests. I was planning to use https://vercel.com/integrations/upstash with this project for the same purpose: https://github.com/trkaplan/opensea-api-proxy

I checked console and network tab. Yeah it sends two request now and four requests sometimes. It may cause the issue to showing different owner address or "undefined" text. 
I think we can add a hook to fetch NFT metadata from opensea against the selected plot id.

**Comment by ssdsr** [comment]
I can take a look at this today. I had a hook created but was getting a lot more re-renders on the map component.

I can take a look at this again today. I'll recreate the hook. If we're not displaying the address on the pop-up, it should be easier to fix

**Comment by ssdsr** [comment]
@trkaplan @blackeagle0188 I added a hook for fetching nft metadata and prevented the duplicate requests. Should only be sending 1 request per active plot change now :thumbsup:

**Comment by ssdsr** [comment]
@trkaplan is implementing proxy/caching in the scope of this task?

I found this walkthrough that seems along the lines of what you were looking for: https://upstash.com/blog/netlify-graph-upstash. I don't have access to the team Vercel account though unfortunately.

**Review by blackeagle0188 — APPROVED** [review]
Checked all updates and it can be merged.

**Comment by ssdsr** [comment]
That's weird I'm only seeing one (split into the preflight and the actual request). Are you seeing differently than this?:
image

**Comment by blackeagle0188** [comment]
> That's weird I'm only seeing one (split into the preflight and the actual request). Are you seeing differently than this?: image

@ssdsr I am seeing this and it sends 2 requests for 1 active plot.
image
Anyway, please change the 2 lines code I mentioned above and let's merge this PR

**Review by blackeagle0188 — APPROVED** [review]

**Comment by trkaplan** [comment]
> @trkaplan is implementing proxy/caching in the scope of this task?
> 
> I found this walkthrough that seems along the lines of what you were looking for: https://upstash.com/blog/netlify-graph-upstash. I don't have access to the team Vercel account though unfortunately.

It does not look like a frontend task, but I think it can be easily implemented with the source code I shared. (open-sea-api-proxy)
Looks like it works now but I think It is important during the launch because many people may use the API after a citydao tweet and they may get error messages from the API

But If you prefer to work on another task, you can work on the showing ENS names task first.

**Pull request merged**
